SAFE_WEB_MARKERS = [
    "SIMULATED_SQLI_MARKER",
    "SIMULATED_XSS_MARKER",
    "SIMULATED_TRAVERSAL_MARKER",
    "SIMULATED_ADMIN_PROBE_MARKER",
]

SAFE_ADMIN_PATHS = ["/admin", "/debug", "/config", "/backup"]
